apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
spec:
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
      - name: go-hello
        image: alexvernize/myhello:latest
        ports:
        - containerPort: 8888
