apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: alexvernize/myhello:latest
  newName: alexvernize/myhello
  newTag: b478c4f43ac7f4b431ad88bcfabb652b3570bb35
