name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build image and push to dockerhub
        uses: docker/build-push-action@v1.1.0
        with:
          username: alexvernize
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: alexvernize/myhello
          tags: ${{ github.sha }}, latest
        # run: |
        #   docker build -t alexvernize/myhello:latest .
        #   echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        #   docker push alexvernize/myhello:latest
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update to k8s
        run: |
          cd k8s
          kustomize edit set image alexvernize/myhello:latest=alexvernize/myhello:${{ github.sha }}
          cat kustomization.yaml
      
      - name: Commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update image to ${{ github.sha }}"
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main

          
      
