name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build image and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          username: alexvernize
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: alexvernize/myhello
          tags: ${{ github.sha }}, latest
        # run: |
        #   docker build -t alexvernize/myhello:latest .
        #   echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        #   docker push alexvernize/myhello:latest
      
